### ISSUE TITLE
Include new menu icons

### ISSUE THREAD

**Issue by ricardoduplos** [openaq/openaq.org#321]
## Tasks

- [ ] Extract from Sketch file
- [ ] Normalize on vector software
- [ ] Export and tidy SVGs
- [ ] Include on menu

---

Seen on the mockups:

### Community
![Screen Shot 2019-09-03 at 11 48 11](https://user-images.githubusercontent.com/1016701/64167551-7ef9b180-ce41-11e9-8a08-570e74f1f1df.png)

### About
![Screen Shot 2019-09-03 at 11 48 16](https://user-images.githubusercontent.com/1016701/64167554-802ade80-ce41-11e9-9d89-ab9aa756fbed.png)

**Comment by jflasher** [comment]
Closing this due to age, but can be reopened if community continues to raise as an issue.
