### ISSUE TITLE
Fix Parameters

### ISSUE THREAD

**Issue by necoline** [openaq/openaq.org#491]
## Problem
Parameters are referenced in a variety of ways throughout the site.
We generally have two data sets for each parameters referencing different `preferredUnits`

e.g. ```{id: 12, name: "CO2", description: "CO2", preferredUnit: "ppm"}, {id: 13, name: "CO2", description: "CO2", preferredUnit: "umol/mol"}```

We shouldn't combine these parameters into one object since that is a level of data mutation that Bitner feels the client would not be comfortable with

## Questions to be answered
- Do parameters return in the same format for each endpoint? I'm not sure of all the endpoints that have parameter values
- What are all the side effects of the current setup?
- Are there more places that parameters are the hardcoded aside from `utils/map-settings`?

## Tasks

- [ ] add a utility that formats the parameter to be easily consumed in all components referencing it (map, location-hub, project-hub)
- [ ] request changes to parameter format on api to be consistent (not sure if this is necessary)
- [ ] add "." to PM2.5 where it appears on the website - filter dropdowns; card text; dashboard pages
- [ ] scale up approach to layer styles to more parameters (currently a fixed definition in utils/map-settings.js)
- [ ] remove duplicate parameters on map
- [ ] add scroll to parameter list

cc: @jvntf @AliceR

**Comment by necoline** [comment]
this was my fix to the duplicate filters. It might be the way we go for a broadly applied util

#475

**Comment by AliceR** [comment]
@jvntf @bitner What is the status of this issue? Seems that a lot of changes happened on the api causing the current branches to fail on several pages. I don't know if I should spend my time on updating the frontend for the new api now, or if this is somewhere in progress?

**Comment by bitner** [comment]
Let's have a quick meetup this morning when everyone gets in.
