### ISSUE TITLE
Dashboard pages visual updates

### ISSUE THREAD

**Issue by rwegener2** [openaq/openaq.org#513]
## Goal
Update the dashboard pages in accordance with the lovely designs that Tânia has made ([wireframe](https://projects.invisionapp.com/d/#/console/20815156/437956789/preview)).  Changes should affect both Locations dashboards ([example](https://openaq-staging.org/#/location/31233)) and Datasets (project) dashboards ([example](https://openaq-staging.org/#/project/27597)).

⭐ tasks are the priority tasks for the Friday milestone

## Sub-tasks
**Top components**
- [x] Change top three components (Details, Latest Measurements, Sources) to grey
- [ ] ~Details component - change the font sizes~
- [x] ⭐ Details component (AQDC datasets only) - display Data Stage (Ex. `https://0jac6b9iac.execute-api.us-east-1.amazonaws.com/v2/locations?sourceName=bay_area_mobile_analysis` @ `sources` -> _index_ -> `lifecycle_stage`)
- [ ] ~Details component - add lcs or gov and mobile or stationary tags in orange~

**Time series**
- [x] ⭐ add unit to the vertical axis
- [x] ⭐ add the label & year to the horizontal axis (this isn't shown in the wireframes - I'd just write "Date" as the label and put the year in parenthesis)
- [x] add unit to the parameter value in the hover text
- [x] remove the lines connecting the individual dots except when hovering over a dot

**Other**
- [x] responsiveness - Latest Measurements number, time series parameter tabs, and temporal coverage parameter tabs overlap when size of the screen is changed ([example](https://openaq-staging.org/#/location/38070))
- [x] Parameters table described below in the [comment](https://github.com/openaq/openaq.org/issues/513#issuecomment-756246567)

### Dataset only sub-tasks ([dataset wireframe](https://projects.invisionapp.com/d/#/console/20815156/437956796/preview))
- [x] Details card - add # of Locations above # of Measurements

### Optional (not project critical)
- [ ] Time Series - pretty up (add color to) the hover value
- [ ] Details - add the little icons to the dates and lat/lon

**Comment by rwegener2** [comment]
@danielfdsilva If it fits in it would also be great if you could add units to the averages in the Parameters table as well.
So something like:
Parameter | Avg | Count
| :------------- | :----------: | -----------: |
PM2.5 | 300 ug/m^3 | 700k
CO conc | 8.23 ppm | 503k
This can supersede The AQDC data stage if you are short on time.  Thanks!

**Comment by rwegener2** [comment]
The unit on the y axis of the time series is present, but has some rendering issues.  It is currently displaying horizontally and smushed into the axis labels.  
<img width="383" alt="Screen Shot 2021-01-10 at 8 38 02 PM" src="https://user-images.githubusercontent.com/35503632/104143081-bf493800-5383-11eb-97d6-a74b0641949e.png">
Fixing this rendering should also be investigated.
- [ ] Fix rendering of unit on y axis of Time Series

**Comment by rwegener2** [comment]
**1/17/20 Update**
The important tasks right now are:
- Dashboards - Change top three components (Details, Latest Measurements, Sources) to grey
- Datasets search - Details card - add # of Locations above # of Measurements

**Comment by rwegener2** [comment]
All high and medium priority items have been completed.  Closing this ticket.
