### ISSUE TITLE
Update Parameter filter emphasizing OpenAQ core parameters

### ISSUE THREAD

**Issue by rwegener2** [openaq/openaq.org#517]
## Goal
We would like to highlight the the original 7 OpenAQ pollutants in the pollutants filters on the Locations and Datasets Hubs by listing them first because those filters will return the most results.

## Details
The 7 original pollutants are:
BC, CO, NO₂, O₃, SO₂, PM2.5, PM10

New pollutants that have been added are:
BC count, CH₄ conc, CO mass, CO₂ conc, NO conc, NO₂ mass, NOx mass, O₃ mass, PM1 mass, SO₂ mass, UFP num, PM0.3 count, PM0.5 count, PM1 count, PM2.5 count, PM5 count, PM10 count, VOC, NOx conc

## Wireframes
Shown below in Tânia's comment.  The [bottommost comment](https://github.com/openaq/openaq.org/issues/517#issuecomment-758550472) is the wireframe to follow.

## Tasks
- [ ] Reorder the parameters
- [ ] Add the 'Core Parameters' and 'Additional Parameters' labels and the associated hover text

## Notes
Someone could start working on this with a hardcoded parameter list, but there is a larger discussion going on about if/how we should note the core OpenAQ parameters.  The results of that discussion will be posted here when the path forward is decided.

**Comment by tania-pires** [comment]
Both category labels should have a short description on hover (Labels and description text are just an example, should be reviewed by a native English speaker).


<img width="1444" alt="Screenshot 2021-01-07 at 10 24 48" src="https://user-images.githubusercontent.com/22524740/103881651-a5cd9500-50d2-11eb-97d5-8522896f01f8.png">
<img width="1439" alt="Screenshot 2021-01-07 at 10 25 00" src="https://user-images.githubusercontent.com/22524740/103881614-9a7a6980-50d2-11eb-8a9d-ae600572e53b.png">

**Comment by rwegener2** [comment]
@tania-pires I love the design solution.  Would you mind updating the text to the following:
* "Original" -> "Core Parameters"
* "Recently Added" -> "Additional Parameters"
hover text: _The following pollutants are less common than the core parameters.  You may have to broaden other search filters when using these parameters to find sufficient results._

If you would just re-post the updated screenshot to your original comment that would be great.

**Comment by rwegener2** [comment]
Backend needs:
- [ ] `isCore` flag associated with the parameters

**Comment by tania-pires** [comment]
### Most recent Mockup![Pollutant-filter](https://user-images.githubusercontent.com/22524740/104300099-f459a580-54bd-11eb-90d4-41b623b817ce.png)

**Comment by tania-pires** [comment]
> @tania-pires I love the design solution. Would you mind updating the text to the following:
> 
> * "Original" -> "Core Parameters"
> * "Recently Added" -> "Additional Parameters"
>   hover text: _The following pollutants are less common than the core parameters.  You may have to broaden other search filters when using these parameters to find sufficient results._
> 
> If you would just re-post the updated screenshot to your original comment that would be great.

**Comment by tania-pires** [comment]
> @tania-pires I love the design solution. Would you mind updating the text to the following:
> 
> * "Original" -> "Core Parameters"
> * "Recently Added" -> "Additional Parameters"
>   hover text: _The following pollutants are less common than the core parameters.  You may have to broaden other search filters when using these parameters to find sufficient results._
> 
> If you would just re-post the updated screenshot to your original comment that would be great.

![Pollutant-filter](https://user-images.githubusercontent.com/22524740/104300265-28cd6180-54be-11eb-979a-07f396bc6277.png)

**Comment by rwegener2** [comment]
Reopening so we can keep using this ticket to track frontend progress on this item
